config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :product_imports, only: [:new, :create] do
    get :job_status, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/product_imports_controller.rb
# frozen_string_literal: true

class ProductImportsController < Spree::Admin::BaseController
  def new; end

  def create
    file_path = FileSaver.new(params[:file].to_io).save
    job_id = ProductsImportWorker.perform_async(file_path)
    render json: { job_id: job_id }
  end

  def job_status
    render json: BackgroundJobStatus.new(params[:job_id]).status
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/product_imports/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:products), spree.admin_products_url %> /
  <%= t(:new_product_import) %>
<% end %>

<div id="error" class="row" style="display: none">
  <div class="alert alert-danger">
    <div class="error-message"></div>
  </div>
</div>

<div id="success" class="row" style="display: none">
  <div class="alert alert-success">
    <div>Products have been imported successfully</div>
  </div>
</div>

<%= form_tag(product_imports_path, method: :post, multipart: true) do %>
  <%= field_set_tag do %>
    <div class="form-group field">
      <%= label_tag(:file, t(:choose_import_file)) %>
      <%= file_field_tag(:file, accept: 'text/csv', id: 'import-input') %>
    </div>

    <div class="form-actions" data-hook="buttons">
      <%= button t(:product_import_submit), 'ok', 'submit', {class: 'btn-success', disabled: true, id: 'import-btn'} %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_products_path, icon: 'remove' %>
    </div>
  <% end %>
<% end %>

<script type='text/javascript'>
  (function($) {
    importBtn = $('#import-btn');
    importInput = $('#import-input');
    progressAlert = $('#progress');
    errorAlert = $('#error');
    successAlert = $('#success')
    var intervalId

    importBtn.click(function(e) {
      e.preventDefault();
      progressAlert.stop(true, true).fadeIn();
      importBtn.prop('disabled', true);
      importInput.prop('disabled', true);
      errorAlert.fadeOut(); 
      successAlert.fadeOut();

      formData = new FormData
      formData.append('file', importInput[0].files[0])

      $.ajax({
        type: 'POST',
        url: '<%= product_imports_path %>',
        contentType: false,
        dataType: 'json',
        data: formData,
        global: false,
        processData: false,
        cache: false,
        success: function(data) { processStatus(data['job_id']); },
        error: function(xhr, textStatus, errorThrown) { 
          displayError(textStatus);
          restoreState();
        }
      });

      function processStatus(jobId) {
        intervalId = setInterval(queryStatus, 1000, jobId)
      }

      function queryStatus(jobId) {
        $.ajax({
          method: 'GET',
          global: false,
          url: '<%= job_status_product_imports_path %>',
          data: { job_id: jobId },
          success: function(data) { handleStatusData(data); },
          error: function(xhr, textStatus, errorThrown) { 
            displayError(textStatus);
            restoreState(); 
          }
        });
      }

      function handleStatusData(data) {
        if(data['status'] == 'working') {
          return;
        }
        
        if(data['status'] == 'complete') {
          displaySuccess();
        } else {
          displayError(data['message']);
        }
        
        restoreState();
      }

      function displayError(message) {
        successAlert.fadeOut();
        errorAlert.fadeIn();
        errorAlert.find('.error-message').text(message);
      }

      function displaySuccess() {
        errorAlert.fadeOut();
        successAlert.fadeIn();
      }

      function restoreState() {
        clearInterval(intervalId);
        importBtn.prop('disabled', false);
        importInput.prop('disabled', false);
        progressAlert.fadeOut();    
      }
    });

    importInput.change(function(e) {
      importBtn.prop('disabled', false);
    });

  })(jQuery)
</script>

app/views/spree/address/_form.html.erb
<% address_id = address_type.chars.first %>

<div class="inner" data-hook=<%="#{address_type}_inner" %>>
  <p class="form-group" id=<%="#{address_id}firstname" %>>
    <%= form.label :firstname do %>
      <%= Spree.t(:first_name) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :firstname, class: 'form-control', required: true %>
  </p>
  <p class="form-group" id=<%="#{address_id}lastname" %>>
    <%= form.label :lastname do %>
      <%= Spree.t(:last_name) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :lastname, class: 'form-control', required: true %>
  </p>
  <% if Spree::Config[:company] %>
    <p class="form-group" id=<%="#{address_id}company" %>>
      <%= form.label :company, Spree.t(:company) %>
      <%= form.text_field :company, class: 'form-control' %>
    </p>
  <% end %>
  <p class="form-group" id=<%="#{address_id}address1" %>>
    <%= form.label :address1 do %>
      <%= Spree.t(:street_address) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :address1, class: 'form-control required' %>
  </p>
  <p class="form-group" id=<%="#{address_id}address2" %>>
    <%= form.label :address2, Spree.t(:street_address_2) %>
    <%= form.text_field :address2, class: 'form-control' %>
  </p>
  <p class="form-group" id=<%="#{address_id}city" %>>
    <%= form.label :city do %>
      <%= Spree.t(:city) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :city, class: 'form-control', required: true %>
  </p>
  <p class="form-group" id=<%="#{address_id}country" %>>
    <%= form.label :country_id do %>
      <%= Spree.t(:country) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <span id=<%="#{address_id}country-selection" %>>
      <%= form.collection_select :country_id, available_countries, :id, :name, {}, { class: 'form-control', required: true } %>
    </span>
  </p>

  <% if Spree::Config[:address_requires_state] %>
    <p class="form-group" id=<%="#{address_id}state" %>>
      <% have_states = !address.country.states.empty? %>
      <%= form.label :state do %>
        <%= Spree.t(:state) %><abbr class='required' title="required" id=<%="#{address_id}state-required"%>>*</abbr>
      <% end %>

      <%== state_elements = [
         form.collection_select(:state_id, address.country.states,
                            :id, :name,
                            {include_blank: true},
                            {class: have_states ? 'form-control' : 'form-control hidden',
                            required: have_states,
                            disabled: !have_states}) +
         form.text_field(:state_name,
                            class: !have_states ? 'form-control' : 'form-control hidden',
                            required: !have_states,
                            disabled: have_states)
         ].join.gsub('"', "'").gsub("\n", "")
      %>
    </p>
      <noscript>
        <%= form.text_field :state_name, class: 'form-control', required: true %>
      </noscript>
  <% end %>

  <p class="form-group" id=<%="#{address_id}zipcode" %>>
    <%= form.label :zipcode do %>
      <%= Spree.t(:zip) %><% if address.require_zipcode? %><abbr class="required" title="required">*</abbr><% end %>
    <% end %>
    <%= form.text_field :zipcode, class: 'form-control', required: address.require_zipcode? %>
  </p>
  <p class="form-group" id=<%="#{address_id}phone" %>>
    <%= form.label :phone do %>
      <%= Spree.t(:phone) %><% if address.require_phone? %><abbr class="required" title="required">*</abbr><% end %>
    <% end %>
    <%= form.phone_field :phone, class: 'form-control', required: address.require_phone? %>
  </p>
  <% if Spree::Config[:alternative_shipping_phone] %>
    <p class="form-group" id=<%="#{address_id}altphone" %>>
      <%= form.label :alternative_phone, Spree.t(:alternative_phone) %>
      <%= form.phone_field :alternative_phone, class: 'form-control' %>
    </p>
  <% end %>
</div>

app/views/spree/admin/products/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Product) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to t(:new_product_import),
                     main_app.new_product_import_path,
                     { class: "btn-success", icon: 'upload', id: 'new_product_import' } %>

  <%= button_link_to Spree.t(:new_product), new_object_url, { class: "btn-success", icon: 'add', id: 'admin_new_product' } %>
<% end if can?(:create, Spree::Product) %>

<% content_for :table_filter do %>
  <div data-hook="admin_products_sidebar">

    <%= search_form_for [:admin, @search] do |f| %>
      <%- locals = {f: f} %>
      <div data-hook="admin_products_index_search" class="row">
        <div class="col-xs-12 col-md-6">
          <div class="form-group">
            <%= f.label :name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, size: 15, class: "form-control js-quick-search-target" %>
          </div>
        </div>
        <div class="col-xs-12 col-md-6">
          <div class="form-group">
            <%= f.label :variants_including_master_sku_cont, Spree.t(:sku) %>
            <%= f.text_field :variants_including_master_sku_cont, size: 15, class: "form-control" %>
          </div>
        </div>
        <div class="col-xs-12 col-md-12">
          <div class="field checkbox">
            <label>
              <%= f.check_box :deleted_at_null, {checked: params[:q][:deleted_at_null] == '0'}, '0', '1' %>
              <%= Spree.t(:show_deleted) %>
            </label>
          </div>

          <div class="field checkbox">
            <label>
              <%= f.check_box :not_discontinued, {checked: params[:q][:not_discontinued] == '0'}, '0', '1' %>
              <%= Spree.t(:show_discontinued ) %>
            </label>
          </div>
        </div>
      </div>
      <div data-hook="admin_products_index_search_buttons" class="form-actions">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>

  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

<% if @collection.any? %>
  <table class="table" id="listing_products">
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= Spree.t(:sku) %></th>
        <th><%= Spree.t(:status) %></th>

        <th colspan="2"><%= sort_link @search,:name, Spree.t(:name), { default_order: "desc" }, {title: 'admin_products_listing_name_title'} %></th>
        <th class="text-center">
          <%= sort_link @search, :master_default_price_amount, Spree.t(:master_price), {}, {title: 'admin_products_listing_price_title'} %>
        </th>
        <th data-hook="admin_products_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |product| %>
          <tr <%== "style='color: red;'" if product.deleted? %> id="<%= spree_dom_id product %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
            <td class="sku"><%= product.sku rescue '' %></td>
            <td class="status"><%= available_status(product) %> </td>
            <td class="image"><%= mini_image product %></td>
            <td><%= link_to product.try(:name), edit_admin_product_path(product) %></td>
            <td class="text-center"><%= product.display_price.to_html rescue '' %></td>
            <td class="actions actions-3 text-right" data-hook="admin_products_index_row_actions">
              <%= link_to_edit product, no_text: true, class: 'edit' if can?(:edit, product) && !product.deleted? %>
              <%= link_to_clone product, no_text: true, class: 'clone' if can?(:clone, product) %>
              <%= link_to_delete product, no_text: true if can?(:delete, product) && !product.deleted? %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Product)) %>,
    <%= link_to Spree.t(:add_one), new_object_url if can?(:create, Spree::Product) %>!
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

app/views/spree/checkout/_address.html.erb
<div class="row">
  <div class="col-sm-6" data-hook="billing_fieldset_wrapper">
    <div class="panel panel-default" id="billing" data-hook>
      <%= form.fields_for :bill_address do |bill_form| %>
        <div class="panel-heading">
          <h3 class="panel-title"><%= Spree.t(:billing_address) %></h3>
        </div>
        <div class="panel-body">
          <%= render partial: 'spree/address/form', locals: { form: bill_form, address_type: 'billing', address: @order.bill_address } %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-sm-6" data-hook="shipping_fieldset_wrapper">
    <div class="panel panel-default" id="shipping" data-hook>
      <%= form.fields_for :ship_address do |ship_form| %>
        <div class="panel-heading">
          <h3 class="panel-title"><%= Spree.t(:shipping_address) %></h3>
        </div>
        <div class="panel-body">
          <p class="field checkbox" data-hook="use_billing">
            <%= label_tag :order_use_billing, id: 'use_billing' do %>
              <%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address? %>
              <%= Spree.t(:use_billing_address) %>
            <% end %>
          </p>
          <%= render partial: 'spree/address/form', locals: { form: ship_form, address_type: 'shipping', address: @order.ship_address } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="well text-right form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success' %>
  <% if try_spree_current_user %>
    <span data-hook="save_user_address" class='save-user-address-wrapper'>
      &nbsp; &nbsp;
      <%= check_box_tag 'save_user_address', '1', try_spree_current_user.respond_to?(:persist_order_address) %>
      <%= label_tag :save_user_address, Spree.t(:save_my_address) %>
    </span>
  <% end %>
</div>

app/views/spree/checkout/_confirm.html.erb
<div class="panel panel-default" id="order_details" data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= Spree.t(:confirm) %></h3>
  </div>
  <div class="panel-body">
    <%= render partial: 'spree/shared/order_details', locals: { order: @order } %>
  </div>
</div>

<div class="well text-right form-buttons" data-hook="buttons">
  <% if @order.using_store_credit? %>
    <%= button_tag Spree.t('store_credit.remove'), name: 'remove_store_credit', class: 'continue btn' %>
  <% end %>
  <%= submit_tag Spree.t(:place_order), class: 'btn btn-lg btn-success' %>
  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/_delivery.html.erb
<div class="panel panel-default" id='shipping_method' data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= Spree.t(:delivery) %></h3>
  </div>
  <div class="panel-body" data-hook="shipping_method_inner">
    <div id="methods">
      <%= form.fields_for :shipments do |ship_form| %>
        <div class="shipment">
          <h4 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:package_from) %>
            <strong class="stock-location-name" data-hook="stock-location-name"><%= ship_form.object.stock_location.name %></strong>
          </h4>

          <table class="table stock-contents" data-hook="stock-contents">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <tr class="active">
                <th></th>
                <th align='left'><%= Spree.t(:item) %></th>
                <th><%= Spree.t(:qty) %></th>
                <th><%= Spree.t(:price) %></th>
              </tr>
            </thead>
            <tbody>
              <% ship_form.object.manifest.each do |item| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(item.variant) %></td>
                  <td class="item-name"><%= item.variant.name %></td>
                  <td class="item-qty"><%= item.quantity %></td>
                  <td class="item-price"><%= display_price(item.variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <h4 class="stock-shipping-method-title"><%= Spree.t(:shipping_method) %></h4>
          <ul class="list-group shipping-methods">
            <% ship_form.object.shipping_rates.each do |rate| %>
              <li class="list-group-item shipping-method">
                <label>
                  <%= ship_form.radio_button :selected_shipping_rate_id, rate.id, data: { behavior: 'shipping-method-selector', cost: rate.display_cost } %>
                  <span class="rate-name"><%= rate.name %></span>
                  <span class="badge rate-cost"><%= rate.display_cost %></span>
                </label>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% if @differentiator.try(:missing?) %>
        <div class="shipment unshippable">
          <h3 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:unshippable_items) %>
          </h3>
          <table class="table stock-contents" data-hook="stock-missing">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= Spree.t(:item) %></th>
              <th><%= Spree.t(:qty) %></th>
              <th><%= Spree.t(:price) %></th>
            </thead>
            <tbody>
              <% @differentiator.missing.each do |variant, quantity| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(variant) %></td>
                  <td class="item-name"><%= variant.name %></td>
                  <td class="item-qty"><%= quantity %></td>
                  <td class="item-price"><%= display_price(variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
    <% if Spree::Config[:shipping_instructions] %>
      <p id="minstrs" data-hook>
        <h4><%= Spree.t(:shipping_instructions) %></h4>
        <%= form.text_area :special_instructions, cols: 40, rows: 4, class: "form-control" %>
      </p>
    <% end %>
  </div>
</div>

<br />

<div class="well text-right form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success' %>
</div>

<%= javascript_include_tag 'spree/frontend/checkout/shipment' %>

app/views/spree/checkout/_payment.html.erb
<div class="panel panel-default" id="payment" data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= Spree.t(:payment_information) %></h3>
  </div>
  <div class="panel-body" data-hook="checkout_payment_step">
    <% if @payment_sources.present? %>
      <div class="card_options">
        <%= radio_button_tag 'use_existing_card', 'yes', true %>
        <label for="use_existing_card_yes">
          <%= Spree.t(:use_existing_cc) %>
        </label>
        <%= radio_button_tag 'use_existing_card', 'no' %>
        <label for="use_existing_card_no">
          <%= Spree.t(:use_new_cc_or_payment_method) %>
        </label>
      </div>

      <div id="existing_cards">
        <p class="form-group" data-hook="existing_cards">
          <table class="existing-credit-card-list">
            <tbody>
              <% @payment_sources.each do |card| %>
                <tr id="<%= dom_id(card,'spree')%>" class="<%= cycle('even', 'odd') %>">
                  <td><%= card.name %></td>
                  <td><%= card.display_number %></td>
                  <td><%= card.month %> / <%= card.year %></td>
                  <td>
                    <%= radio_button_tag "order[existing_card]", card.id, (card == @payment_sources.first), { class: "existing-cc-radio" }  %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </p>
      </div>
    <% end %>

    <%= render partial: 'spree/checkout/payment/storecredit' %>

    <ul class="list-group" id="payment-method-fields" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li class="list-group-item">
          <label>
            <%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.available_payment_methods.first %>
            <%= Spree.t(method.name, scope: :payment_methods, default: method.name) %>
          </label>
        </li>
      <% end %>
    </ul>

    <ul class="nav" id="payment-methods" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li id="payment_method_<%= method.id %>" class="<%= 'last' if method == @order.available_payment_methods.last %>" data-hook>
          <fieldset>
            <%= render partial: "spree/checkout/payment/#{method.method_type}", locals: { payment_method: method } %>
          </fieldset>
        </li>
      <% end %>
    </ul>


    <% if Spree::Frontend::Config[:coupon_codes_enabled] %>
      <p class='field' data-hook='coupon_code'>
        <%= form.label :coupon_code %>
        <%= form.text_field :coupon_code, class: 'form-control' %>
      </p>
    <% end %>
  </div>
</div>

<div class="well text-right form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success primary' %>
  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/_summary.html.erb
<h3><%= Spree.t(:order_summary) %></h3>

<table class="table" data-hook="order_summary">
  <tbody>
    <tr data-hook="item_total">
      <td><strong><%= Spree.t(:item_total) %>:</strong></td>
      <td><strong><%= order.display_item_total.to_html %></strong></td>
    </tr>

    <% if order.line_item_adjustments.nonzero.exists? %>
      <tbody data-hook="order_details_promotion_adjustments">
        <% order.line_item_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
          <tr class="total">
            <td><%= label %></td>
            <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>

    <tbody data-hook="order_details_tax_adjustments">
      <% order.all_adjustments.nonzero.tax.eligible.group_by(&:label).each do |label, adjustments| %>
        <tr class="total">
          <td><%= label %></td>
          <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
        </tr>
      <% end %>
    </tbody>

    <% if order.passed_checkout_step?("address") && order.shipments.any? %>
      <tr data-hook="shipping_total">
        <td><%= Spree.t(:shipping_total) %>:</td>
        <% shipping_total = Spree::Money.new(order.shipments.to_a.sum(&:cost), currency: order.currency) %>
        <td data-hook='shipping-total' data-currency='<%= Money::Currency.find(order.currency).symbol %>' thousands-separator='<%= shipping_total.thousands_separator %>' decimal-mark='<%= shipping_total.decimal_mark %>'><%= shipping_total.to_html %></td>
      </tr>

      <% if order.shipment_adjustments.nonzero.exists? %>
        <tbody data-hook="order_details_shipment_promotion_adjustments">
          <% order.shipment_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
            <tr class="total">
              <td><%= label %>:</td>
              <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    <% end %>

    <% if order.adjustments.nonzero.eligible.exists? %>
      <tbody id="summary-order-charges" data-hook>
        <% order.adjustments.nonzero.eligible.each do |adjustment| %>
        <% next if (adjustment.source_type == 'Spree::TaxRate') and (adjustment.amount == 0) %>
          <tr class="total">
            <td><%= adjustment.label %>:</td>
            <td><%= adjustment.display_amount.to_html %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>

    <tr data-hook="order_total">
      <td><strong><%= Spree.t(:order_total) %>:</strong></td>
      <td><strong><span id='summary-order-total' class="lead text-primary" data-currency=<%= Money::Currency.find(order.currency).symbol %>><%= order.display_total.to_html %></span></strong></td>
    </tr>

    <% if order.using_store_credit? %>
      <tr data-hook="order_details_store_credit">
        <td><strong><%= Spree.t(:store_credit_name) %>:</strong></td>
        <td><span id='summary-store-credit'><%= order.display_total_applied_store_credit.to_html %></span></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/checkout/edit.html.erb
<% @body_id = 'checkout-page' %>
<% content_for :google_analytics do %>
  <%= render partial: 'spree/shared/google_checkout.js', locals: { order: @order, step_number: (@order.checkout_steps.index(@order.state) + 1) } %>
<% end %>

<%= render partial: 'spree/shared/trackers/segment/checkout_step_viewed.js',
            formats: :js,
            locals: { order: @order } %>

<div id="checkout" data-hook>
  <%= render partial: 'spree/shared/error_messages', locals: { target: @order } %>

  <div class="row" data-hook="checkout_header">
    <div class="col-sm-3">
      <h1 data-hook="checkout_title"><%= Spree.t(:checkout) %></h1>
    </div>
    <div class="col-sm-9" data-hook="checkout_progress">
      <%= checkout_progress %>
    </div>
  </div>

  <div class="row" data-hook="checkout_content">
    <div class="<%= if @order.state != 'confirm' then 'col-md-9' else 'col-md-12' end %>" data-hook="checkout_form_wrapper">
      <%= form_for @order, url: update_checkout_path(@order.state), html: { id: "checkout_form_#{@order.state}" } do |form| %>
        <% if @order.state == 'address' || !@order.email? %>
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="form-group">
                <%= form.label :email %>
                <%= form.email_field :email, class: 'form-control', required: true %>
              </div>
            </div>
          </div>
        <% end %>
        <%= form.hidden_field :state_lock_version %>
        <%= render @order.state, form: form %>
      <% end %>
    </div>
    <% if @order.state != 'confirm' %>
      <div id="checkout-summary" data-hook="checkout_summary_box" class="col-md-3">
        <%= render partial: 'summary', locals: { order: @order } %>
      </div>
    <% end %>
  </div>
</div>

<script>
  Spree.current_order_id = "<%= @order.number %>"
  Spree.current_order_token = "<%= @order.guest_token %>"
</script>

app/views/spree/products/_promotions.html.erb
<% promotions = @product.possible_promotions %>

<% if promotions.any? %>
  <div id="promotions">
    <h3><%= Spree.t(:promotions) %></h3>
    <% promotions.each do |promotion| %>
    <div class="well well-sm">
      <h4><%= promotion.name %></h4>
      <p><%= promotion.description %></p>
      <% if promotion.products.any? %>
        <ul>
          <% promotion.products.each do |product| %>
            <li><%= link_to product.name, product_path(product) %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <% end %>
  </div>
<% end %>